/**
 * Condition form field configuration
 */

import { tagsFieldConfig, getTodayEndOfDay } from './shared';

export const conditionFormFields = [
  {
    name: 'diagnosis',
    type: 'text',
    labelKey: 'medical:conditions.diagnosis.label',
    placeholderKey: 'medical:conditions.diagnosis.placeholder',
    required: true,
    descriptionKey: 'medical:conditions.diagnosis.description',
    gridColumn: 12,
  },
  {
    name: 'status',
    type: 'select',
    labelKey: 'shared:fields.status',
    descriptionKey: 'medical:conditions.status.description',
    gridColumn: 6,
    dynamicOptions: 'conditionStatus',
  },
  {
    name: 'severity',
    type: 'select',
    labelKey: 'shared:fields.severity',
    placeholderKey: 'shared:labels.selectSeverityLevel',
    descriptionKey: 'medical:conditions.severity.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'severity',
  },
  {
    name: 'medication_id',
    type: 'select',
    labelKey: 'medical:conditions.relatedMedication.label',
    placeholderKey: 'medical:conditions.relatedMedication.placeholder',
    descriptionKey: 'medical:conditions.relatedMedication.description',
    gridColumn: 12,
    searchable: true,
    clearable: true,
    dynamicOptions: 'medications',
  },
  {
    name: 'onset_date',
    type: 'date',
    labelKey: 'shared:fields.onsetDate',
    placeholderKey: 'medical:conditions.onsetDate.placeholder',
    descriptionKey: 'medical:conditions.onsetDate.description',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'end_date',
    type: 'date',
    labelKey: 'shared:labels.endDate',
    placeholderKey: 'medical:conditions.endDate.placeholder',
    descriptionKey: 'medical:conditions.endDate.description',
    gridColumn: 6,
    maxDate: getTodayEndOfDay,
  },
  {
    name: 'icd10_code',
    type: 'text',
    labelKey: 'shared:fields.icd10Code',
    placeholderKey: 'medical:conditions.icd10Code.placeholder',
    descriptionKey: 'medical:conditions.icd10Code.description',
    gridColumn: 4,
    maxLength: 10,
  },
  {
    name: 'snomed_code',
    type: 'text',
    labelKey: 'shared:fields.snomedCode',
    placeholderKey: 'medical:conditions.snomedCode.placeholder',
    descriptionKey: 'medical:conditions.snomedCode.description',
    gridColumn: 4,
    maxLength: 20,
  },
  {
    name: 'code_description',
    type: 'text',
    labelKey: 'shared:fields.codeDescription',
    placeholderKey: 'medical:conditions.codeDescription.placeholder',
    descriptionKey: 'medical:conditions.codeDescription.description',
    gridColumn: 4,
    maxLength: 500,
  },
  {
    name: 'notes',
    type: 'textarea',
    labelKey: 'shared:tabs.notes',
    placeholderKey: 'common:fields.notes.placeholder',
    descriptionKey: 'medical:conditions.notes.description',
    gridColumn: 12,
    minRows: 4,
    maxRows: 8,
  },
  tagsFieldConfig,
];
