/**
 * Emergency Contact form field configuration
 */

export const emergencyContactFormFields = [
  {
    name: 'name',
    type: 'text',
    labelKey: 'shared:fields.fullName',
    placeholderKey: 'medical:emergencyContacts.form.name.placeholder',
    required: true,
    descriptionKey: 'medical:emergencyContacts.form.name.description',
    gridColumn: 7,
  },
  {
    name: 'relationship',
    type: 'select',
    labelKey: 'medical:emergencyContacts.form.relationship.label',
    placeholderKey: 'shared:fields.selectRelationship',
    descriptionKey: 'medical:emergencyContacts.form.relationship.description',
    required: true,
    gridColumn: 5,
    dynamicOptions: 'relationships',
  },
  {
    name: 'phone_number',
    type: 'tel',
    labelKey: 'medical:emergencyContacts.form.primaryPhone.label',
    placeholderKey: 'medical:emergencyContacts.form.primaryPhone.placeholder',
    required: true,
    descriptionKey: 'medical:emergencyContacts.form.primaryPhone.description',
    gridColumn: 6,
    maxLength: 20,
  },
  {
    name: 'secondary_phone',
    type: 'tel',
    labelKey: 'medical:emergencyContacts.form.secondaryPhone.label',
    placeholderKey: 'medical:emergencyContacts.form.secondaryPhone.placeholder',
    descriptionKey: 'medical:emergencyContacts.form.secondaryPhone.description',
    gridColumn: 6,
    maxLength: 20,
  },
  {
    name: 'email',
    type: 'email',
    labelKey: 'shared:fields.emailAddress',
    placeholderKey: 'medical:emergencyContacts.form.email.placeholder',
    descriptionKey: 'medical:emergencyContacts.form.email.description',
    gridColumn: 12,
  },
  {
    name: 'address',
    type: 'text',
    labelKey: 'medical:emergencyContacts.form.address.label',
    placeholderKey: 'medical:emergencyContacts.form.address.placeholder',
    descriptionKey: 'medical:emergencyContacts.form.address.description',
    gridColumn: 12,
  },
  {
    name: 'is_primary',
    type: 'checkbox',
    labelKey: 'medical:emergencyContacts.form.isPrimary.label',
    descriptionKey: 'medical:emergencyContacts.form.isPrimary.description',
    gridColumn: 6,
  },
  {
    name: 'is_active',
    type: 'checkbox',
    labelKey: 'medical:emergencyContacts.form.isActive.label',
    descriptionKey: 'medical:emergencyContacts.form.isActive.description',
    gridColumn: 6,
  },
  {
    name: 'notes',
    type: 'textarea',
    labelKey: 'shared:tabs.notes',
    placeholderKey: 'medical:emergencyContacts.form.notes.placeholder',
    descriptionKey: 'medical:emergencyContacts.form.notes.description',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
];
