/**
 * Immunization form field configuration
 */

import { tagsFieldConfig } from './shared';

export const immunizationFormFields = [
  {
    name: 'vaccine_name',
    type: 'text',
    labelKey: 'medical:immunizations.vaccineName.label',
    placeholderKey: 'medical:immunizations.vaccineName.placeholder',
    required: true,
    descriptionKey: 'medical:immunizations.vaccineName.description',
    gridColumn: 12,
  },
  {
    name: 'date_administered',
    type: 'date',
    labelKey: 'shared:fields.dateAdministered',
    placeholderKey: 'medical:immunizations.dateAdministered.placeholder',
    required: true,
    descriptionKey: 'medical:immunizations.dateAdministered.description',
    gridColumn: 8,
  },
  {
    name: 'dose_number',
    type: 'number',
    labelKey: 'medical:immunizations.doseNumber.label',
    placeholderKey: 'medical:immunizations.doseNumber.placeholder',
    descriptionKey: 'medical:immunizations.doseNumber.description',
    gridColumn: 4,
    min: 1,
    max: 10,
  },
  {
    name: 'lot_number',
    type: 'text',
    labelKey: 'medical:immunizations.lotNumber.label',
    placeholderKey: 'medical:immunizations.lotNumber.placeholder',
    descriptionKey: 'medical:immunizations.lotNumber.description',
    gridColumn: 6,
  },
  {
    name: 'ndc_number',
    type: 'text',
    labelKey: 'shared:fields.ndcNumber',
    placeholderKey: 'medical:immunizations.ndcNumber.placeholder',
    descriptionKey: 'medical:immunizations.ndcNumber.description',
    gridColumn: 6,
  },
  {
    name: 'manufacturer',
    type: 'select',
    labelKey: 'medical:immunizations.manufacturer.label',
    placeholderKey: 'medical:immunizations.manufacturer.placeholder',
    descriptionKey: 'medical:immunizations.manufacturer.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'manufacturers',
  },
  {
    name: 'site',
    type: 'select',
    labelKey: 'medical:immunizations.site.label',
    placeholderKey: 'medical:immunizations.site.placeholder',
    descriptionKey: 'medical:immunizations.site.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'sites',
  },
  {
    name: 'route',
    type: 'select',
    labelKey: 'medical:immunizations.route.label',
    placeholderKey: 'medical:immunizations.route.placeholder',
    descriptionKey: 'medical:immunizations.route.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'routes',
  },
  {
    name: 'expiration_date',
    type: 'date',
    labelKey: 'medical:immunizations.expirationDate.label',
    placeholderKey: 'medical:immunizations.expirationDate.placeholder',
    descriptionKey: 'medical:immunizations.expirationDate.description',
    gridColumn: 12,
  },
  {
    name: 'location',
    type: 'text',
    labelKey: 'shared:labels.location',
    placeholderKey: 'medical:immunizations.location.placeholder',
    descriptionKey: 'medical:immunizations.location.description',
    gridColumn: 12,
  },
  {
    name: 'notes',
    type: 'textarea',
    labelKey: 'shared:tabs.notes',
    placeholderKey: 'medical:immunizations.notes.placeholder',
    descriptionKey: 'medical:immunizations.notes.description',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  tagsFieldConfig,
];
