/**
 * Insurance form field configuration
 */

import { tagsFieldConfig } from './shared';

export const insuranceFormFields = [
  // === SECTION 1: Basic Insurance Information ===
  {
    name: '_divider_basic',
    type: 'divider',
    labelKey: 'medical:insurance.form.dividers.basicInfo',
    gridColumn: 12,
  },
  {
    name: 'insurance_type',
    type: 'select',
    labelKey: 'medical:insurance.form.insuranceType.label',
    placeholderKey: 'medical:insurance.form.insuranceType.placeholder',
    required: true,
    descriptionKey: 'medical:insurance.form.insuranceType.description',
    gridColumn: 6,
    options: [
      {
        value: 'medical',
        labelKey: 'medical:insurance.form.insuranceType.options.medical',
      },
      {
        value: 'dental',
        labelKey: 'medical:insurance.form.insuranceType.options.dental',
      },
      {
        value: 'vision',
        labelKey: 'medical:insurance.form.insuranceType.options.vision',
      },
      {
        value: 'prescription',
        labelKey: 'medical:insurance.form.insuranceType.options.prescription',
      },
    ],
  },
  {
    name: 'company_name',
    type: 'text',
    labelKey: 'medical:insurance.form.companyName.label',
    placeholderKey: 'medical:insurance.form.companyName.placeholder',
    required: true,
    descriptionKey: 'medical:insurance.form.companyName.description',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'plan_name',
    type: 'text',
    labelKey: 'medical:insurance.form.planName.label',
    placeholderKey: 'medical:insurance.form.planName.placeholder',
    descriptionKey: 'medical:insurance.form.planName.description',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'employer_group',
    type: 'text',
    labelKey: 'medical:insurance.form.employerGroup.label',
    placeholderKey: 'medical:insurance.form.employerGroup.placeholder',
    descriptionKey: 'medical:insurance.form.employerGroup.description',
    gridColumn: 6,
    maxLength: 255,
  },

  // === SECTION 2: Member Information ===
  {
    name: '_divider_member',
    type: 'divider',
    labelKey: 'medical:insurance.form.dividers.memberInfo',
    gridColumn: 12,
  },
  {
    name: 'member_name',
    type: 'text',
    labelKey: 'medical:insurance.form.memberName.label',
    placeholderKey: 'medical:insurance.form.memberName.placeholder',
    required: true,
    descriptionKey: 'medical:insurance.form.memberName.description',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'member_id',
    type: 'text',
    labelKey: 'medical:insurance.form.memberId.label',
    placeholderKey: 'medical:insurance.form.memberId.placeholder',
    required: true,
    descriptionKey: 'medical:insurance.form.memberId.description',
    gridColumn: 6,
    maxLength: 100,
  },
  {
    name: 'policy_holder_name',
    type: 'text',
    labelKey: 'medical:insurance.form.policyHolderName.label',
    placeholderKey: 'medical:insurance.form.policyHolderName.placeholder',
    descriptionKey: 'medical:insurance.form.policyHolderName.description',
    gridColumn: 6,
    maxLength: 255,
  },
  {
    name: 'relationship_to_holder',
    type: 'select',
    labelKey: 'medical:insurance.form.relationshipToHolder.label',
    placeholderKey: 'shared:fields.selectRelationship',
    descriptionKey: 'medical:insurance.form.relationshipToHolder.description',
    gridColumn: 6,
    clearable: true,
    options: [
      { value: 'self', labelKey: 'shared:fields.self' },
      {
        value: 'spouse',
        labelKey: 'medical:insurance.form.relationshipToHolder.options.spouse',
      },
      {
        value: 'child',
        labelKey: 'medical:insurance.form.relationshipToHolder.options.child',
      },
      {
        value: 'dependent',
        labelKey:
          'medical:insurance.form.relationshipToHolder.options.dependent',
      },
      { value: 'other', labelKey: 'shared:fields.other' },
    ],
  },
  {
    name: 'group_number',
    type: 'text',
    labelKey: 'shared:labels.groupNumber',
    placeholderKey: 'medical:insurance.form.groupNumber.placeholder',
    descriptionKey: 'medical:insurance.form.groupNumber.description',
    gridColumn: 6,
    maxLength: 100,
  },

  // === SECTION 3: Coverage Period & Status ===
  {
    name: '_divider_coverage',
    type: 'divider',
    labelKey: 'medical:insurance.form.dividers.coveragePeriodStatus',
    gridColumn: 12,
  },
  {
    name: 'effective_date',
    type: 'date',
    labelKey: 'medical:insurance.form.effectiveDate.label',
    placeholderKey: 'medical:insurance.form.effectiveDate.placeholder',
    required: true,
    descriptionKey: 'medical:insurance.form.effectiveDate.description',
    gridColumn: 6,
  },
  {
    name: 'expiration_date',
    type: 'date',
    labelKey: 'medical:insurance.form.expirationDate.label',
    placeholderKey: 'medical:insurance.form.expirationDate.placeholder',
    descriptionKey: 'medical:insurance.form.expirationDate.description',
    gridColumn: 6,
  },
  {
    name: 'status',
    type: 'select',
    labelKey: 'shared:fields.status',
    placeholderKey: 'medical:insurance.form.status.placeholder',
    required: true,
    descriptionKey: 'medical:insurance.form.status.description',
    gridColumn: 6,
    clearable: false,
    options: [
      { value: 'active', labelKey: 'shared:labels.active' },
      { value: 'inactive', labelKey: 'shared:labels.inactive' },
      {
        value: 'expired',
        labelKey: 'medical:insurance.form.status.options.expired',
      },
      { value: 'pending', labelKey: 'shared:fields.pending' },
    ],
  },
  {
    name: 'is_primary',
    type: 'checkbox',
    labelKey: 'medical:insurance.form.isPrimary.label',
    descriptionKey: 'medical:insurance.form.isPrimary.description',
    gridColumn: 6,
  },

  // === SECTION 4: Contact Information ===
  {
    name: '_divider_contact',
    type: 'divider',
    labelKey: 'shared:fields.contactInformation',
    gridColumn: 12,
  },
  {
    name: 'customer_service_phone',
    type: 'tel',
    labelKey: 'medical:insurance.form.customerServicePhone.label',
    placeholderKey: 'medical:insurance.form.customerServicePhone.placeholder',
    descriptionKey: 'medical:insurance.form.customerServicePhone.description',
    gridColumn: 6,
    maxLength: 20,
    showFor: ['medical', 'dental', 'vision', 'prescription'],
  },
  {
    name: 'preauth_phone',
    type: 'tel',
    labelKey: 'medical:insurance.form.preauthPhone.label',
    placeholderKey: 'medical:insurance.form.customerServicePhone.placeholder',
    descriptionKey: 'medical:insurance.form.preauthPhone.description',
    gridColumn: 6,
    maxLength: 20,
    showFor: ['medical'],
  },
  {
    name: 'provider_services_phone',
    type: 'tel',
    labelKey: 'medical:insurance.form.providerServicesPhone.label',
    placeholderKey: 'medical:insurance.form.customerServicePhone.placeholder',
    descriptionKey: 'medical:insurance.form.providerServicesPhone.description',
    gridColumn: 6,
    maxLength: 20,
    showFor: ['medical', 'dental'],
  },
  {
    name: 'website_url',
    type: 'url',
    labelKey: 'medical:insurance.form.websiteUrl.label',
    placeholderKey: 'medical:insurance.form.websiteUrl.placeholder',
    descriptionKey: 'medical:insurance.form.websiteUrl.description',
    gridColumn: 6,
    showFor: ['medical', 'dental', 'vision', 'prescription'],
  },
  {
    name: 'claims_address',
    type: 'textarea',
    labelKey: 'medical:insurance.form.claimsAddress.label',
    placeholderKey: 'medical:insurance.form.claimsAddress.placeholder',
    descriptionKey: 'medical:insurance.form.claimsAddress.description',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
    showFor: ['medical', 'dental', 'vision'],
  },

  // === SECTION 5: Coverage Details (Type-Specific) ===
  {
    name: '_divider_coverage_details',
    type: 'divider',
    labelKey: 'medical:insurance.form.dividers.coverageDetails',
    gridColumn: 12,
  },

  // Medical Insurance Fields
  {
    name: 'primary_care_physician',
    type: 'text',
    labelKey: 'medical:insurance.form.primaryCarePhysician.label',
    placeholderKey: 'medical:insurance.form.primaryCarePhysician.placeholder',
    descriptionKey: 'medical:insurance.form.primaryCarePhysician.description',
    gridColumn: 6,
    maxLength: 255,
    showFor: ['medical'],
  },
  {
    name: 'deductible_individual',
    type: 'number',
    labelKey: 'medical:insurance.form.deductibleIndividual.label',
    placeholderKey: 'medical:insurance.form.deductibleIndividual.placeholder',
    descriptionKey: 'medical:insurance.form.deductibleIndividual.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'deductible_family',
    type: 'number',
    labelKey: 'medical:insurance.form.deductibleFamily.label',
    placeholderKey: 'medical:insurance.form.deductibleFamily.placeholder',
    descriptionKey: 'medical:insurance.form.deductibleFamily.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_primary_care',
    type: 'number',
    labelKey: 'medical:insurance.form.copayPrimaryCare.label',
    placeholderKey: 'medical:insurance.form.copayPrimaryCare.placeholder',
    descriptionKey: 'medical:insurance.form.copayPrimaryCare.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_specialist',
    type: 'number',
    labelKey: 'medical:insurance.form.copaySpecialist.label',
    placeholderKey: 'shared:fields.eg50',
    descriptionKey: 'medical:insurance.form.copaySpecialist.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_emergency_room',
    type: 'number',
    labelKey: 'medical:insurance.form.copayEmergencyRoom.label',
    placeholderKey: 'medical:insurance.form.copayEmergencyRoom.placeholder',
    descriptionKey: 'medical:insurance.form.copayEmergencyRoom.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },
  {
    name: 'copay_urgent_care',
    type: 'number',
    labelKey: 'medical:insurance.form.copayUrgentCare.label',
    placeholderKey: 'medical:insurance.form.copayUrgentCare.placeholder',
    descriptionKey: 'medical:insurance.form.copayUrgentCare.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['medical'],
  },

  // Medical Insurance Plan Type
  {
    name: 'plan_type',
    type: 'select',
    labelKey: 'medical:insurance.form.planType.label',
    placeholderKey: 'medical:insurance.form.planType.placeholder',
    descriptionKey: 'medical:insurance.form.planType.description',
    gridColumn: 6,
    showFor: ['medical'],
    options: [
      { value: 'ppo', labelKey: 'medical:insurance.form.planType.options.ppo' },
      { value: 'hmo', labelKey: 'medical:insurance.form.planType.options.hmo' },
      { value: 'epo', labelKey: 'medical:insurance.form.planType.options.epo' },
      { value: 'pos', labelKey: 'medical:insurance.form.planType.options.pos' },
      {
        value: 'hdhp',
        labelKey: 'medical:insurance.form.planType.options.hdhp',
      },
      {
        value: 'indemnity',
        labelKey: 'medical:insurance.form.planType.options.indemnity',
      },
      { value: 'other', labelKey: 'shared:fields.other' },
    ],
  },

  // Dental Insurance Plan Type
  {
    name: 'dental_plan_type',
    type: 'select',
    labelKey: 'medical:insurance.form.dentalPlanType.label',
    placeholderKey: 'medical:insurance.form.dentalPlanType.placeholder',
    descriptionKey: 'medical:insurance.form.dentalPlanType.description',
    gridColumn: 6,
    showFor: ['dental'],
    options: [
      {
        value: 'dppo',
        labelKey: 'medical:insurance.form.dentalPlanType.options.dppo',
      },
      {
        value: 'dhmo',
        labelKey: 'medical:insurance.form.dentalPlanType.options.dhmo',
      },
      {
        value: 'indemnity',
        labelKey: 'medical:insurance.form.planType.options.indemnity',
      },
      {
        value: 'discount',
        labelKey: 'medical:insurance.form.dentalPlanType.options.discount',
      },
      { value: 'other', labelKey: 'shared:fields.other' },
    ],
  },

  // Vision Insurance Plan Type
  {
    name: 'vision_plan_type',
    type: 'select',
    labelKey: 'medical:insurance.form.visionPlanType.label',
    placeholderKey: 'medical:insurance.form.visionPlanType.placeholder',
    descriptionKey: 'medical:insurance.form.visionPlanType.description',
    gridColumn: 6,
    showFor: ['vision'],
    options: [
      {
        value: 'vision_ppo',
        labelKey: 'medical:insurance.form.visionPlanType.options.visionPpo',
      },
      {
        value: 'vision_hmo',
        labelKey: 'medical:insurance.form.visionPlanType.options.visionHmo',
      },
      {
        value: 'vision_discount',
        labelKey:
          'medical:insurance.form.visionPlanType.options.visionDiscount',
      },
      { value: 'other', labelKey: 'shared:fields.other' },
    ],
  },

  // Prescription Plan Type
  {
    name: 'prescription_plan_type',
    type: 'select',
    labelKey: 'medical:insurance.form.prescriptionPlanType.label',
    placeholderKey: 'medical:insurance.form.prescriptionPlanType.placeholder',
    descriptionKey: 'medical:insurance.form.prescriptionPlanType.description',
    gridColumn: 6,
    showFor: ['prescription'],
    options: [
      {
        value: 'formulary',
        labelKey:
          'medical:insurance.form.prescriptionPlanType.options.formulary',
      },
      {
        value: 'tiered_copay',
        labelKey:
          'medical:insurance.form.prescriptionPlanType.options.tieredCopay',
      },
      {
        value: 'medicare_part_d',
        labelKey:
          'medical:insurance.form.prescriptionPlanType.options.medicarePartD',
      },
      {
        value: 'integrated',
        labelKey:
          'medical:insurance.form.prescriptionPlanType.options.integrated',
      },
      { value: 'other', labelKey: 'shared:fields.other' },
    ],
  },
  {
    name: 'annual_maximum',
    type: 'number',
    labelKey: 'medical:insurance.form.annualMaximum.label',
    placeholderKey: 'medical:insurance.form.annualMaximum.placeholder',
    descriptionKey: 'medical:insurance.form.annualMaximum.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['dental'],
  },
  {
    name: 'preventive_coverage',
    type: 'number',
    labelKey: 'medical:insurance.form.preventiveCoverage.label',
    placeholderKey: 'medical:insurance.form.preventiveCoverage.placeholder',
    descriptionKey: 'medical:insurance.form.preventiveCoverage.description',
    gridColumn: 4,
    min: 0,
    max: 100,
    step: 1,
    showFor: ['dental'],
  },
  {
    name: 'basic_coverage',
    type: 'number',
    labelKey: 'medical:insurance.form.basicCoverage.label',
    placeholderKey: 'medical:insurance.form.basicCoverage.placeholder',
    descriptionKey: 'medical:insurance.form.basicCoverage.description',
    gridColumn: 6,
    min: 0,
    max: 100,
    step: 1,
    showFor: ['dental'],
  },
  {
    name: 'major_coverage',
    type: 'number',
    labelKey: 'medical:insurance.form.majorCoverage.label',
    placeholderKey: 'shared:fields.eg50',
    descriptionKey: 'medical:insurance.form.majorCoverage.description',
    gridColumn: 6,
    min: 0,
    max: 100,
    step: 1,
    showFor: ['dental'],
  },

  // Vision Insurance Fields
  {
    name: 'exam_copay',
    type: 'number',
    labelKey: 'medical:insurance.form.examCopay.label',
    placeholderKey: 'medical:insurance.form.examCopay.placeholder',
    descriptionKey: 'medical:insurance.form.examCopay.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['vision'],
  },
  {
    name: 'frame_allowance',
    type: 'number',
    labelKey: 'medical:insurance.form.frameAllowance.label',
    placeholderKey: 'medical:insurance.form.frameAllowance.placeholder',
    descriptionKey: 'medical:insurance.form.frameAllowance.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['vision'],
  },
  {
    name: 'lens_coverage',
    type: 'text',
    labelKey: 'medical:insurance.form.lensCoverage.label',
    placeholderKey: 'medical:insurance.form.lensCoverage.placeholder',
    descriptionKey: 'medical:insurance.form.lensCoverage.description',
    gridColumn: 6,
    showFor: ['vision'],
  },
  {
    name: 'contact_allowance',
    type: 'number',
    labelKey: 'medical:insurance.form.contactAllowance.label',
    placeholderKey: 'medical:insurance.form.contactAllowance.placeholder',
    descriptionKey: 'medical:insurance.form.contactAllowance.description',
    gridColumn: 6,
    min: 0,
    step: 1,
    showFor: ['vision'],
  },

  // Prescription Insurance Fields
  {
    name: 'bin_number',
    type: 'text',
    labelKey: 'medical:insurance.form.binNumber.label',
    placeholderKey: 'medical:insurance.form.binNumber.placeholder',
    descriptionKey: 'medical:insurance.form.binNumber.description',
    gridColumn: 4,
    maxLength: 10,
    showFor: ['prescription'],
    required: true,
    requiredFor: ['prescription'],
  },
  {
    name: 'pcn_number',
    type: 'text',
    labelKey: 'medical:insurance.form.pcnNumber.label',
    placeholderKey: 'medical:insurance.form.pcnNumber.placeholder',
    descriptionKey: 'medical:insurance.form.pcnNumber.description',
    gridColumn: 4,
    maxLength: 10,
    showFor: ['prescription'],
    required: true,
    requiredFor: ['prescription'],
  },
  {
    name: 'rxgroup',
    type: 'text',
    labelKey: 'medical:insurance.form.rxgroup.label',
    placeholderKey: 'medical:insurance.form.rxgroup.placeholder',
    descriptionKey: 'medical:insurance.form.rxgroup.description',
    gridColumn: 4,
    maxLength: 15,
    showFor: ['prescription'],
  },
  {
    name: 'copay_generic',
    type: 'number',
    labelKey: 'medical:insurance.form.copayGeneric.label',
    placeholderKey: 'medical:insurance.form.copayGeneric.placeholder',
    descriptionKey: 'medical:insurance.form.copayGeneric.description',
    gridColumn: 4,
    min: 0,
    step: 1,
    showFor: ['prescription'],
  },
  {
    name: 'copay_brand',
    type: 'number',
    labelKey: 'medical:insurance.form.copayBrand.label',
    placeholderKey: 'medical:insurance.form.copayBrand.placeholder',
    descriptionKey: 'medical:insurance.form.copayBrand.description',
    gridColumn: 4,
    min: 0,
    step: 1,
    showFor: ['prescription'],
  },
  {
    name: 'copay_specialty',
    type: 'number',
    labelKey: 'medical:insurance.form.copaySpecialty.label',
    placeholderKey: 'shared:fields.eg50',
    descriptionKey: 'medical:insurance.form.copaySpecialty.description',
    gridColumn: 4,
    min: 0,
    step: 1,
    showFor: ['prescription'],
  },
  {
    name: 'pharmacy_network_info',
    type: 'textarea',
    labelKey: 'medical:insurance.form.pharmacyNetworkInfo.label',
    placeholderKey: 'medical:insurance.form.pharmacyNetworkInfo.placeholder',
    descriptionKey: 'medical:insurance.form.pharmacyNetworkInfo.description',
    gridColumn: 12,
    minRows: 2,
    maxRows: 4,
    showFor: ['prescription'],
  },

  // === SECTION 6: Additional Information ===
  {
    name: '_divider_notes',
    type: 'divider',
    labelKey: 'medical:insurance.form.dividers.additionalInfo',
    gridColumn: 12,
  },
  {
    name: 'notes',
    type: 'textarea',
    labelKey: 'shared:tabs.notes',
    placeholderKey: 'medical:insurance.form.notes.placeholder',
    descriptionKey: 'medical:insurance.form.notes.description',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  tagsFieldConfig,
];
