/**
 * Lab Result form field configuration
 */

import { tagsFieldConfig } from './shared';

export const labResultFormFields = [
  {
    name: 'test_name',
    type: 'text',
    labelKey: 'medical:labResults.testName.label',
    placeholderKey: 'medical:labResults.testName.placeholder',
    descriptionKey: 'medical:labResults.testName.description',
    required: true,
    gridColumn: 8,
  },
  {
    name: 'test_code',
    type: 'text',
    labelKey: 'shared:fields.testCode',
    placeholderKey: 'medical:labResults.testCode.placeholder',
    descriptionKey: 'medical:labResults.testCode.description',
    gridColumn: 4,
  },
  {
    name: 'test_category',
    type: 'select',
    labelKey: 'medical:labResults.testCategory.label',
    placeholderKey: 'shared:labels.selectCategory',
    descriptionKey: 'medical:labResults.testCategory.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'categories',
  },
  {
    name: 'test_type',
    type: 'select',
    labelKey: 'medical:labResults.testTypeField.label',
    placeholderKey: 'medical:labResults.testTypeField.placeholder',
    descriptionKey: 'medical:labResults.testTypeField.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'testTypes',
  },
  {
    name: 'facility',
    type: 'text',
    labelKey: 'medical:labResults.testingFacility.label',
    placeholderKey: 'medical:labResults.testingFacility.placeholder',
    descriptionKey: 'medical:labResults.testingFacility.description',
    gridColumn: 6,
  },
  {
    name: 'practitioner_id',
    type: 'select',
    labelKey: 'shared:labels.orderingPractitioner',
    placeholderKey: 'shared:labels.selectPractitioner',
    descriptionKey: 'medical:labResults.orderingPractitioner.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    dynamicOptions: 'practitioners',
  },
  {
    name: 'status',
    type: 'select',
    labelKey: 'medical:labResults.testStatus.label',
    placeholderKey: 'medical:labResults.testStatus.placeholder',
    descriptionKey: 'medical:labResults.testStatus.description',
    gridColumn: 6,
    dynamicOptions: 'statuses',
  },
  {
    name: 'labs_result',
    type: 'select',
    labelKey: 'shared:labels.labResult',
    placeholderKey: 'medical:labResults.labResult.placeholder',
    descriptionKey: 'medical:labResults.labResult.description',
    gridColumn: 6,
    clearable: true,
    dynamicOptions: 'results',
  },
  {
    name: 'ordered_date',
    type: 'date',
    labelKey: 'shared:labels.orderedDate',
    placeholderKey: 'medical:labResults.orderedDate.placeholder',
    descriptionKey: 'medical:labResults.orderedDate.description',
    gridColumn: 6,
  },
  {
    name: 'completed_date',
    type: 'date',
    labelKey: 'shared:labels.completedDate',
    placeholderKey: 'medical:labResults.completedDate.placeholder',
    descriptionKey: 'medical:labResults.completedDate.description',
    gridColumn: 6,
  },
  {
    name: 'notes',
    type: 'textarea',
    labelKey: 'shared:fields.additionalNotes',
    placeholderKey: 'medical:labResults.additionalNotes.placeholder',
    descriptionKey: 'medical:labResults.additionalNotes.description',
    gridColumn: 12,
    minRows: 4,
    maxRows: 12,
    maxLength: 5000,
  },
  tagsFieldConfig,
];
