/**
 * Medication form field configuration
 *
 * Each field declares a `section` that maps to a form tab:
 *   'basic'   - Basic Info tab
 *   'details' - Details tab
 *   'notes'   - Notes tab
 */

import {
  MEDICATION_TYPES,
  MEDICATION_TYPE_LABELS,
} from '../../constants/medicationTypes';
import { tagsFieldConfig } from './shared';

export const medicationFormFields = [
  {
    name: 'medication_name',
    section: 'basic',
    type: 'text',
    labelKey: 'shared:labels.medicationName',
    placeholderKey: 'medical:medications.medicationName.placeholder',
    descriptionKey: 'medical:medications.medicationName.description',
    required: true,
    gridColumn: 6,
    minLength: 2,
    maxLength: 255,
  },
  {
    name: 'alternative_name',
    section: 'basic',
    type: 'text',
    labelKey: 'medical:medications.alternativeName.label',
    placeholderKey: 'medical:medications.alternativeName.placeholder',
    descriptionKey: 'medical:medications.alternativeName.description',
    required: false,
    gridColumn: 6,
    minLength: 2,
    maxLength: 100,
  },
  {
    name: 'medication_type',
    section: 'basic',
    type: 'select',
    labelKey: 'shared:labels.medicationType',
    placeholderKey: 'medical:medications.medicationType.placeholder',
    descriptionKey: 'medical:medications.medicationType.description',
    required: true,
    gridColumn: 6,
    options: Object.keys(MEDICATION_TYPES).map(key => ({
      value: MEDICATION_TYPES[key],
      label: MEDICATION_TYPE_LABELS[MEDICATION_TYPES[key]],
    })),
  },
  {
    name: 'dosage',
    section: 'basic',
    type: 'text',
    labelKey: 'medical:medications.dosage.label',
    placeholderKey: 'medical:medications.dosage.placeholder',
    descriptionKey: 'medical:medications.dosage.description',
    gridColumn: 6,
  },
  {
    name: 'frequency',
    section: 'basic',
    type: 'text',
    labelKey: 'medical:medications.frequency.label',
    placeholderKey: 'medical:medications.frequency.placeholder',
    descriptionKey: 'medical:medications.frequency.description',
    gridColumn: 6,
  },
  {
    name: 'route',
    section: 'basic',
    type: 'select',
    labelKey: 'medical:medications.route.label',
    placeholderKey: 'medical:medications.route.placeholder',
    descriptionKey: 'medical:medications.route.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    options: [
      { value: 'oral', labelKey: 'shared:fields.oral' },
      {
        value: 'injection',
        labelKey: 'medical:medications.route.options.injection',
      },
      {
        value: 'topical',
        labelKey: 'medical:medications.route.options.topical',
      },
      {
        value: 'intravenous',
        labelKey: 'medical:medications.route.options.intravenous',
      },
      {
        value: 'intramuscular',
        labelKey: 'medical:medications.route.options.intramuscular',
      },
      {
        value: 'subcutaneous',
        labelKey: 'medical:medications.route.options.subcutaneous',
      },
      {
        value: 'inhalation',
        labelKey: 'medical:medications.route.options.inhalation',
      },
      { value: 'nasal', labelKey: 'shared:fields.nasal' },
      { value: 'rectal', labelKey: 'medical:medications.route.options.rectal' },
      {
        value: 'sublingual',
        labelKey: 'medical:medications.route.options.sublingual',
      },
    ],
  },
  {
    name: 'indication',
    section: 'basic',
    type: 'text',
    labelKey: 'medical:medications.indication.label',
    placeholderKey: 'medical:medications.indication.placeholder',
    descriptionKey: 'medical:medications.indication.description',
    gridColumn: 12,
  },
  {
    name: 'status',
    section: 'details',
    type: 'select',
    labelKey: 'shared:fields.status',
    descriptionKey: 'common:fields.status.description',
    gridColumn: 4,
    options: [
      { value: 'active', labelKey: 'shared:labels.active' },
      { value: 'stopped', labelKey: 'common:status.stopped' },
      { value: 'on-hold', labelKey: 'common:status.onHold' },
      { value: 'completed', labelKey: 'shared:fields.completed' },
    ],
  },
  {
    name: 'effective_period_start',
    section: 'details',
    type: 'date',
    labelKey: 'common:fields.startDate.label',
    placeholderKey: 'common:fields.startDate.placeholder',
    descriptionKey: 'common:fields.startDate.description',
    gridColumn: 4,
  },
  {
    name: 'effective_period_end',
    section: 'details',
    type: 'date',
    labelKey: 'common:fields.endDate.label',
    placeholderKey: 'common:fields.endDate.placeholder',
    descriptionKey: 'common:fields.endDate.description',
    gridColumn: 4,
  },
  {
    name: 'practitioner_id',
    section: 'details',
    type: 'select',
    labelKey: 'medical:medications.prescribingProvider.label',
    placeholderKey: 'medical:medications.prescribingProvider.placeholder',
    descriptionKey: 'medical:medications.prescribingProvider.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    maxDropdownHeight: 200,
    dynamicOptions: 'practitioners',
  },
  {
    name: 'pharmacy_id',
    section: 'details',
    type: 'select',
    labelKey: 'medical:medications.pharmacy.label',
    placeholderKey: 'medical:medications.pharmacy.placeholder',
    descriptionKey: 'medical:medications.pharmacy.description',
    gridColumn: 6,
    searchable: true,
    clearable: true,
    maxDropdownHeight: 200,
    dynamicOptions: 'pharmacies',
  },
  {
    name: 'notes',
    section: 'notes',
    type: 'textarea',
    labelKey: 'shared:tabs.notes',
    placeholderKey: 'common:fields.notes.placeholder',
    descriptionKey: 'common:fields.notes.description',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  {
    name: 'side_effects',
    section: 'notes',
    type: 'textarea',
    labelKey: 'shared:labels.sideEffects',
    placeholderKey: 'medical:medications.sideEffects.placeholder',
    descriptionKey: 'medical:medications.sideEffects.description',
    gridColumn: 12,
    minRows: 3,
    maxRows: 6,
  },
  { ...tagsFieldConfig, section: 'details' },
];
