"""remove_overly_restrictive_invitation_constraint

Revision ID: 26dd25579d9f
Revises: 5769cf0b4d86
Create Date: 2025-07-19 17:40:39.408545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26dd25579d9f'
down_revision = '5769cf0b4d86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_active_invitation', 'invitations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_active_invitation', 'invitations', ['sent_by_user_id', 'sent_to_user_id', 'invitation_type'])
    # ### end Alembic commands ###
