"""update junction tables to reference symptoms table

Revision ID: 9b1705e3de39
Revises: 8df261bb269f
Create Date: 2025-10-11 11:28:09.647956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1705e3de39'
down_revision = '8df261bb269f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('symptom_conditions_symptom_id_fkey', 'symptom_conditions', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_conditions', 'symptoms', ['symptom_id'], ['id'])
    op.drop_constraint('symptom_medications_symptom_id_fkey', 'symptom_medications', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_medications', 'symptoms', ['symptom_id'], ['id'])
    op.drop_constraint('symptom_treatments_symptom_id_fkey', 'symptom_treatments', type_='foreignkey')
    op.create_foreign_key(None, 'symptom_treatments', 'symptoms', ['symptom_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'symptom_treatments', type_='foreignkey')
    op.create_foreign_key('symptom_treatments_symptom_id_fkey', 'symptom_treatments', 'symptom_entries', ['symptom_id'], ['id'])
    op.drop_constraint(None, 'symptom_medications', type_='foreignkey')
    op.create_foreign_key('symptom_medications_symptom_id_fkey', 'symptom_medications', 'symptom_entries', ['symptom_id'], ['id'])
    op.drop_constraint(None, 'symptom_conditions', type_='foreignkey')
    op.create_foreign_key('symptom_conditions_symptom_id_fkey', 'symptom_conditions', 'symptom_entries', ['symptom_id'], ['id'])
    # ### end Alembic commands ###
