"""add indexes to symptom junction tables

Revision ID: f5e2f39331cc
Revises: 9b1705e3de39
Create Date: 2025-10-11 12:04:42.455201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e2f39331cc'
down_revision = '9b1705e3de39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_symptom_condition_condition_id', 'symptom_conditions', ['condition_id'], unique=False)
    op.create_index('idx_symptom_condition_symptom_id', 'symptom_conditions', ['symptom_id'], unique=False)
    op.create_unique_constraint('uq_symptom_condition', 'symptom_conditions', ['symptom_id', 'condition_id'])
    op.create_index('idx_symptom_medication_medication_id', 'symptom_medications', ['medication_id'], unique=False)
    op.create_index('idx_symptom_medication_symptom_id', 'symptom_medications', ['symptom_id'], unique=False)
    op.create_unique_constraint('uq_symptom_medication', 'symptom_medications', ['symptom_id', 'medication_id'])
    op.create_index('idx_symptom_treatment_symptom_id', 'symptom_treatments', ['symptom_id'], unique=False)
    op.create_index('idx_symptom_treatment_treatment_id', 'symptom_treatments', ['treatment_id'], unique=False)
    op.create_unique_constraint('uq_symptom_treatment', 'symptom_treatments', ['symptom_id', 'treatment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_symptom_treatment', 'symptom_treatments', type_='unique')
    op.drop_index('idx_symptom_treatment_treatment_id', table_name='symptom_treatments')
    op.drop_index('idx_symptom_treatment_symptom_id', table_name='symptom_treatments')
    op.drop_constraint('uq_symptom_medication', 'symptom_medications', type_='unique')
    op.drop_index('idx_symptom_medication_symptom_id', table_name='symptom_medications')
    op.drop_index('idx_symptom_medication_medication_id', table_name='symptom_medications')
    op.drop_constraint('uq_symptom_condition', 'symptom_conditions', type_='unique')
    op.drop_index('idx_symptom_condition_symptom_id', table_name='symptom_conditions')
    op.drop_index('idx_symptom_condition_condition_id', table_name='symptom_conditions')
    # ### end Alembic commands ###
