"""Add NDC number to immunizations table

Revision ID: e19727dae6b0
Revises: 2a6a93043ebb
Create Date: 2025-09-20 10:11:49.147491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e19727dae6b0'
down_revision = '2a6a93043ebb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immunizations', sa.Column('ndc_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('immunizations', 'ndc_number')
    # ### end Alembic commands ###
