"""Add paperless_task_uuid field to entity_files

Revision ID: ecb8117c18d8
Revises: 2d8c4aa8f2c2
Create Date: 2025-08-02 19:50:15.285664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb8117c18d8'
down_revision = '2d8c4aa8f2c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_files', sa.Column('paperless_task_uuid', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_files', 'paperless_task_uuid')
    # ### end Alembic commands ###
