"""add_enhanced_fields_to_encounters

Revision ID: 3fa18fb7b87b
Revises: 98515df1c54f
Create Date: 2025-07-01 22:04:56.658493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa18fb7b87b'
down_revision = '98515df1c54f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('visit_type', sa.String(), nullable=True))
    op.add_column('encounters', sa.Column('chief_complaint', sa.String(), nullable=True))
    op.add_column('encounters', sa.Column('diagnosis', sa.String(), nullable=True))
    op.add_column('encounters', sa.Column('treatment_plan', sa.String(), nullable=True))
    op.add_column('encounters', sa.Column('follow_up_instructions', sa.String(), nullable=True))
    op.add_column('encounters', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('encounters', sa.Column('location', sa.String(), nullable=True))
    op.add_column('encounters', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'priority')
    op.drop_column('encounters', 'location')
    op.drop_column('encounters', 'duration_minutes')
    op.drop_column('encounters', 'follow_up_instructions')
    op.drop_column('encounters', 'treatment_plan')
    op.drop_column('encounters', 'diagnosis')
    op.drop_column('encounters', 'chief_complaint')
    op.drop_column('encounters', 'visit_type')
    # ### end Alembic commands ###
