"""add_backup_records_table

Revision ID: d87e96e7e961
Revises: b499032f9b2b
Create Date: 2025-06-23 16:38:13.041653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87e96e7e961'
down_revision = 'b499032f9b2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('compression_used', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('backup_records')
    # ### end Alembic commands ###
