"""add cascade delete to activity logs patient_id

Revision ID: 87a9508a7478
Revises: 2f7e836195bb
Create Date: 2025-07-21 21:26:25.340125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a9508a7478'
down_revision = '2f7e836195bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_logs_patient_id_fkey', 'activity_logs', type_='foreignkey')
    op.create_foreign_key(None, 'activity_logs', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.create_foreign_key('activity_logs_patient_id_fkey', 'activity_logs', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###
