"""procedure_add_anathesia

Revision ID: 5cb8b82b39fb
Revises: 82683ba6bc3e
Create Date: 2025-07-06 13:11:20.371417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb8b82b39fb'
down_revision = '82683ba6bc3e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('anesthesia_type', sa.String(), nullable=True))
    op.add_column('procedures', sa.Column('anesthesia_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('procedures', 'anesthesia_notes')
    op.drop_column('procedures', 'anesthesia_type')
    # ### end Alembic commands ###
