"""add_severity_to_condition

Revision ID: 128b34e77fc7
Revises: 0b23860a8fe9
Create Date: 2025-07-02 19:38:20.676100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128b34e77fc7'
down_revision = '0b23860a8fe9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conditions', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('icd10_code', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('snomed_code', sa.String(), nullable=True))
    op.add_column('conditions', sa.Column('code_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conditions', 'code_description')
    op.drop_column('conditions', 'snomed_code')
    op.drop_column('conditions', 'icd10_code')
    op.drop_column('conditions', 'severity')
    # ### end Alembic commands ###
