"""Fix cascade delete for lab_test_components foreign key

Revision ID: 4edca606d456
Revises: 442af1bdd4b8
Create Date: 2025-09-30 09:08:05.713792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edca606d456'
down_revision = '442af1bdd4b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
