"""Add phone_number, website, and rating to practitioners

Revision ID: d6dd7b7e8b03
Revises: 4b0e8e733ae8
Create Date: 2025-06-17 18:28:28.664254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dd7b7e8b03'
down_revision = '4b0e8e733ae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('practitioners', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('practitioners', sa.Column('website', sa.String(), nullable=True))
    op.add_column('practitioners', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('practitioners', 'rating')
    op.drop_column('practitioners', 'website')
    op.drop_column('practitioners', 'phone_number')
    # ### end Alembic commands ###
