"""Add symptom entries table

Revision ID: 17068ca95ee4
Revises: cf881eaef7d8
Create Date: 2025-10-10 21:02:01.294563

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17068ca95ee4'
down_revision = 'cf881eaef7d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptom_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('symptom_name', sa.String(length=200), nullable=False),
    sa.Column('recorded_date', sa.DateTime(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pain_scale', sa.Integer(), nullable=True),
    sa.Column('resolved_date', sa.DateTime(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symptom_entries_patient_date', 'symptom_entries', ['patient_id', 'recorded_date'], unique=False)
    op.create_index('idx_symptom_entries_patient_id', 'symptom_entries', ['patient_id'], unique=False)
    op.create_index('idx_symptom_entries_severity', 'symptom_entries', ['severity'], unique=False)
    op.create_index('idx_symptom_entries_status', 'symptom_entries', ['status'], unique=False)
    op.alter_column('medications', 'medication_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_patient_shares_invitation_id', table_name='patient_shares')
    op.drop_index('idx_patient_shares_lookup', table_name='patient_shares')
    op.drop_constraint('fk_patient_share_invitation', 'patient_shares', type_='foreignkey')
    op.create_foreign_key(None, 'patient_shares', 'invitations', ['invitation_id'], ['id'])
    op.alter_column('standardized_tests', 'is_common',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('standardized_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('standardized_tests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_standardized_tests_test_name_fts', table_name='standardized_tests')
    op.create_index(op.f('ix_standardized_tests_category'), 'standardized_tests', ['category'], unique=False)
    op.create_index(op.f('ix_standardized_tests_id'), 'standardized_tests', ['id'], unique=False)
    op.create_index(op.f('ix_standardized_tests_is_common'), 'standardized_tests', ['is_common'], unique=False)
    op.create_index(op.f('ix_standardized_tests_loinc_code'), 'standardized_tests', ['loinc_code'], unique=True)
    op.create_index(op.f('ix_standardized_tests_short_name'), 'standardized_tests', ['short_name'], unique=False)
    op.create_index(op.f('ix_standardized_tests_test_name'), 'standardized_tests', ['test_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standardized_tests_test_name'), table_name='standardized_tests')
    op.drop_index(op.f('ix_standardized_tests_short_name'), table_name='standardized_tests')
    op.drop_index(op.f('ix_standardized_tests_loinc_code'), table_name='standardized_tests')
    op.drop_index(op.f('ix_standardized_tests_is_common'), table_name='standardized_tests')
    op.drop_index(op.f('ix_standardized_tests_id'), table_name='standardized_tests')
    op.drop_index(op.f('ix_standardized_tests_category'), table_name='standardized_tests')
    op.create_index('idx_standardized_tests_test_name_fts', 'standardized_tests', [sa.text("to_tsvector('english'::regconfig, test_name::text)")], unique=False)
    op.alter_column('standardized_tests', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('standardized_tests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('standardized_tests', 'is_common',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'patient_shares', type_='foreignkey')
    op.create_foreign_key('fk_patient_share_invitation', 'patient_shares', 'invitations', ['invitation_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_patient_shares_lookup', 'patient_shares', ['patient_id', 'shared_with_user_id', 'is_active'], unique=False)
    op.create_index('idx_patient_shares_invitation_id', 'patient_shares', ['invitation_id'], unique=False)
    op.alter_column('medications', 'medication_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'prescription'::character varying"),
               existing_nullable=False)
    op.drop_index('idx_symptom_entries_status', table_name='symptom_entries')
    op.drop_index('idx_symptom_entries_severity', table_name='symptom_entries')
    op.drop_index('idx_symptom_entries_patient_id', table_name='symptom_entries')
    op.drop_index('idx_symptom_entries_patient_date', table_name='symptom_entries')
    op.drop_table('symptom_entries')
    # ### end Alembic commands ###
