"""Add location field to immunizations

Revision ID: 2a6a93043ebb
Revises: add_session_timeout
Create Date: 2025-09-15 14:11:19.999333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a6a93043ebb'
down_revision = 'add_session_timeout'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immunizations', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('immunizations', 'location')
    # ### end Alembic commands ###
