"""update_pharmacy_table

Revision ID: f5f0951c16cb
Revises: 4de5c8a43c0e
Create Date: 2025-06-21 10:15:16.308630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f0951c16cb'
down_revision = '4de5c8a43c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('brand', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('street_address', sa.String(), nullable=False))
    op.add_column('pharmacies', sa.Column('city', sa.String(), nullable=False))
    op.add_column('pharmacies', sa.Column('state', sa.String(), nullable=False))
    op.add_column('pharmacies', sa.Column('zip_code', sa.String(), nullable=False))
    op.add_column('pharmacies', sa.Column('country', sa.String(), nullable=False))
    op.add_column('pharmacies', sa.Column('store_number', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('fax_number', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('hours', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('drive_through', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('twenty_four_hour', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('specialty_services', sa.String(), nullable=True))
    op.add_column('pharmacies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('pharmacies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('pharmacies', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pharmacies', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pharmacies', 'updated_at')
    op.drop_column('pharmacies', 'created_at')
    op.drop_column('pharmacies', 'specialty_services')
    op.drop_column('pharmacies', 'twenty_four_hour')
    op.drop_column('pharmacies', 'drive_through')
    op.drop_column('pharmacies', 'hours')
    op.drop_column('pharmacies', 'fax_number')
    op.drop_column('pharmacies', 'store_number')
    op.drop_column('pharmacies', 'country')
    op.drop_column('pharmacies', 'zip_code')
    op.drop_column('pharmacies', 'state')
    op.drop_column('pharmacies', 'city')
    op.drop_column('pharmacies', 'street_address')
    op.drop_column('pharmacies', 'brand')
    # ### end Alembic commands ###
