"""Add vaccine trade name to immunizations table

Revision ID: 33b89582fb06
Revises: e19727dae6b0
Create Date: 2025-09-20 11:39:02.762727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33b89582fb06'
down_revision = 'e19727dae6b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('immunizations', sa.Column('vaccine_trade_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('immunizations', 'vaccine_trade_name')
    # ### end Alembic commands ###
