"""update_pharmacy_table-2

Revision ID: 78e6a9f0c46d
Revises: f5f0951c16cb
Create Date: 2025-06-21 11:10:39.401015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78e6a9f0c46d'
down_revision = 'f5f0951c16cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pharmacies', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pharmacies', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pharmacies', 'state',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pharmacies', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pharmacies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pharmacies', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pharmacies', 'zip_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pharmacies', 'state',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pharmacies', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pharmacies', 'street_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
